// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBORavIkg-EhKKF-rCrHM9j1NlIgT-Jo3k',
    appId: '1:537840054800:web:9fe5f6ce914b262d765095',
    messagingSenderId: '537840054800',
    projectId: 'bhuvan-testapp',
    authDomain: 'bhuvan-testapp.firebaseapp.com',
    storageBucket: 'bhuvan-testapp.appspot.com',
    measurementId: 'G-DQJ5M3YZNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqHnAPCq9yCw29N73ziNWHdMMC0PvlIZo',
    appId: '1:537840054800:android:280f7a24afcaf9ca765095',
    messagingSenderId: '537840054800',
    projectId: 'bhuvan-testapp',
    storageBucket: 'bhuvan-testapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS3BjjOgMrHaVDaDFesSp0g_9Ie8ONs9E',
    appId: '1:537840054800:ios:30bdd62aa94e4df0765095',
    messagingSenderId: '537840054800',
    projectId: 'bhuvan-testapp',
    storageBucket: 'bhuvan-testapp.appspot.com',
    iosBundleId: 'com.example.testapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS3BjjOgMrHaVDaDFesSp0g_9Ie8ONs9E',
    appId: '1:537840054800:ios:f0785be1a7881721765095',
    messagingSenderId: '537840054800',
    projectId: 'bhuvan-testapp',
    storageBucket: 'bhuvan-testapp.appspot.com',
    iosBundleId: 'com.example.testapp.RunnerTests',
  );
}
